Suppress missing-field-initializers warning pre-clang6
semantics.c:1551:32: error: missing field 'len' initializer
    fb_value_t index = { { { 0 } }, 0, 0 };

See https://reviews.llvm.org/D28148 and
related https://reviews.llvm.org/rL314838