Fix build with gcc-8
gcc 8 enables a warning about strncpy that might leave the destination
string without a terminating null character. This breaks the build:

In function ‘read_thash_identifier’,
    inlined from ‘flatcc_verify_buffer_header’ at .../src/runtime/verifier.c:468:15:
.../src/runtime/verifier.c:114:5: error: ‘strncpy’ specified bound 4 equals destination size [-Werror=stringop-truncation]
     strncpy((char *)&id, identifier, sizeof(id));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.../src/runtime/json_printer.c: In function ‘accept_header’:
.../src/runtime/json_printer.c:1023:9: error: ‘strncpy’ specified bound 4 equals destination size [-Werror=stringop-truncation]
         strncpy((char *)&id2, fid, FLATBUFFERS_IDENTIFIER_SIZE);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.../src/compiler/codegen_schema.c: In function ‘flatbuffers_has_identifier.constprop’:
.../include/flatcc/reflection/flatbuffers_common_reader.h:436:3: error: ‘strncpy’ output truncated before terminating nul copying 4 bytes from a string of the same length [-Werror=stringop-truncation]
   strncpy((char *)&id2, fid, sizeof(id2));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Use memcpy instead, since memcpy is not expected to leave a null
terminator.